#!/bin/bash

# cd ..
# path=$PWD/data/$1


function validName(){
    if [[ $1 =~ ^[a-zA-Z]+$  ]]
    then
        return 0
    else
        return 1
    fi
}

function checkDbDir(){
    if [[ -d $1 ]]
    then 
        return 0
    else
        return 1
    fi 
}


# START FROM HERE

# connect 

echo "connecting to database "

# $1 -> database name
path=$PWD/data/$1


#echo $path


if validName $1
then
    if checkDbDir $path
    then

        echo "connected to '$1' database"
        db_name=$1
        # propt="$1 >"
        # PS3=$propt
    else 
        echo "database not exists"
    fi 
fi
# change prompt name to the Connected database name

# instead of shql
export connected_db=$db_name
#echo $connected_db
