#!/bin/bash


# query 
#  cmd     $1    $2
#  update  table tablename

if [ $# -eq 0 ] #number of arguments is zero
then
    echo "update: not a valid query "

elif [ $1 == "table" ]
then
    if [ -z $connected_db  ]
    then  
        echo "you need to connect to a database first"
    else 
        update_table.sh $2
    fi 
else 
    echo "update: not a valid query argument "

fi